trainer:
  target: trainer.TrainerDifIRLPIPS

model:
  target: models.unet.UNetModelSwin
  ckpt_path: "/workspace/ResShift/logs/train/2026-01-04-06-21/ema_ckpts/ema_model_15000.pth"
  params:
    image_size: 64
    in_channels: 3
    model_channels: 160
    out_channels: 3
    attention_resolutions: [64, 32, 16, 8]
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 192
    window_size: 8
    mlp_ratio: 4
    cond_lq: True
    lq_size: 256

diffusion:
  target: models.script_util.create_gaussian_diffusion
  params:
    sf: 1
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 4
    min_noise_level: 0.2
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True

autoencoder:
  target: ldm.models.autoencoder.VQModelTorch
  ckpt_path: "/workspace/ResShift/weights/autoencoder_vq_f4.pth"
  tune_decoder: False
  params:
    lora_tune_decoder: False
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      padding_mode: zeros

lpips:
  net: alex

data:
  train:
    type: paired
    params:
      dir_path: "/workspace/dataset/train/noisy"
      dir_path_extra: "/workspace/dataset/train/clean"
      transform_type: rcrop_aug_norm
      transform_kwargs:
        pass_aug: True
        pch_size: 256
        mean: 0.5
        std: 0.5
        max_value: 255
      im_exts: jpg
      length: ~
      recursive: False
  val:
    type: paired
    params:
      dir_path: "/workspace/dataset/val/noisy"
      dir_path_extra: "/workspace/dataset/val/clean"
      transform_type: rcrop_aug_norm 
      transform_kwargs: 
        pass_aug: True
        pch_size: 256
        mean: ${data.train.params.transform_kwargs.mean}
        std: ${data.train.params.transform_kwargs.std}
        max_value: ${data.train.params.transform_kwargs.max_value}
      im_exts: jpg
      length: 64
      recursive: False

train:
  lr: 5e-5
  lr_min: 1e-5
  lr_schedule: cosin
  warmup_iterations: 0
  
  batch: [32, 1] 
  
  microbatch: 10
  
  num_workers: 16
  prefetch_factor: 4
  
  weight_decay: 0
  ema_rate: 0.999
  
  iterations: 15000
  
  save_freq: 2500
  log_freq: [50, 50, 2]
  
  loss_coef: [1.0, 4.0, 0.0]
  local_logging: True
  tf_logging: False
  
  # Validation settings
  use_ema_val: True
  val_freq: 2000
  val_y_channel: True
  val_resolution: ${model.params.lq_size}
  val_padding_mode: reflect
  
  use_amp: True
  seed: 123456
  global_seeding: False
  
  compile:
    flag: False
    mode: reduce-overhead